version: "2"

services:
    odoo10:
        image: tecnativa/ocb:10.0
        tty: true
        env_file:
            - ./env/odoo10.env
        ports:
            - "8069"
            - "8072"
        volumes:
            - ./addons/available:/opt/odoo/available:ro,z
            - ./addons/enabled:/opt/odoo/extra-addons:ro,z
        links:
            - "db10:db"
            - wdb
            - smtp
        volumes_from:
            - odoodata10

    odoodata10:
        image: tecnativa/ocb:10.0
        command: "true"

    db10:
        image: postgres:9.2
        env_file:
            - ./env/db.env
        volumes_from:
            - dbdata10

    dbdata10:
        image: postgres:9.2
        command: "true"

    smtp:
        image: tecnativa/postfix-relay
        env_file:
            - ./env/smtp.env

    wdb:
        image: yajo/wdb-server
        ports:
            - "1984:1984"
            - "19840:19840"
