version: "2"

services:
    odoo8:
        image: tecnativa/ocb:8.0
        tty: true
        env_file:
            - ./env/odoo.env
        ports:
            - "80:8069"
            - "8072:8072"
        volumes:
            - ./addons/available:/opt/odoo/available:ro,z
            - ./addons/enabled:/opt/odoo/extra-addons:ro,z
        links:
            - "db8:db"
            - wdb
            - smtp
        volumes_from:
            - odoodata8

    odoodata8:
        image: tecnativa/ocb:8.0
        command: "true"

    db8:
        image: postgres:9.2
        env_file:
            - ./env/db.env
        volumes_from:
            - dbdata8

    dbdata8:
        image: postgres:9.2
        command: "true"

    smtp:
        image: tecnativa/postfix-relay
        env_file:
            - ./env/smtp.env

    wdb:
        image: yajo/wdb-server
        ports:
            - "1984:1984"
            - "19840:19840"
